### ISSUE TITLE
Build error: " Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings)."

### ISSUE THREAD

**Issue by C-Lunn** [jim-easterbrook/pyctools-pal#1]
Hi,

I get the following issue when trying to run `python setup.py build`:

```
python setup.py build
Compiling src/pyctools/components/pal/true4fsccore.pyx because it changed.
Compiling src/pyctools/components/pal/transformcore.pyx because it changed.
[1/2] Cythonizing src/pyctools/components/pal/transformcore.pyx
Error compiling Cython file:
------------------------------------------------------------
...
            if x == x_ref and y == y_ref:
                # at Fsc, so no attenuation
                for j in range(y_blk):
                    for i in range(x_blk):
                        out_data[j, y, i, x] = in_data[j, y, i, x]
            elif mode == 'l':
                        ^
------------------------------------------------------------
src/pyctools/components/pal/transformcore.pyx:47:25: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).
Error compiling Cython file:
------------------------------------------------------------
...
                            out_data[j, y, i, x] = in_val
                            out_data[j, y_ref, i, x_ref] = ref_val * m_in / m_ref
                        else:
                            out_data[j, y, i, x] = in_val * m_ref / m_in
                            out_data[j, y_ref, i, x_ref] = ref_val
            elif mode == '2':
                        ^
------------------------------------------------------------
src/pyctools/components/pal/transformcore.pyx:61:25: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    ext_modules = cythonize(find_ext_modules(), compiler_directives={
  File "/usr/local/lib64/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib64/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/pyctools/components/pal/transformcore.pyx
```

Changing `elif mode == 'l'` to `elif mode == 'l'.encode('ascii')` (and likewise for `2`) appears to resolve this, but I am unsure if this will cause issues down the line. 

Any advice would be appreciated. Thank you.

**Comment by jim-easterbrook** [comment]
That looks like a sensible solution. I haven't worked on this stuff at all recently so haven't found this bug myself. All that's needed is a way to select the decoding mode - a simple integer would do, but I liked having the first letter of the human readable mode (set in transform.py) so I could remember what each mode is.
