### ISSUE TITLE
compile fails on python 3.11/cython 0.29.33 ?

### ISSUE THREAD

**Issue by Randrianasulu** [jim-easterbrook/pyctools-pal#2]
```
Compiling src/pyctools/components/pal/transformcore.pyx because it changed.
Compiling src/pyctools/components/pal/true4fsccore.pyx because it changed.
[1/2] Cythonizing src/pyctools/components/pal/transformcore.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            if x == x_ref and y == y_ref:
                # at Fsc, so no attenuation
                for j in range(y_blk):
                    for i in range(x_blk):
                        out_data[j, y, i, x] = in_data[j, y, i, x]
            elif mode == 'l':
                        ^
------------------------------------------------------------

src/pyctools/components/pal/transformcore.pyx:47:25: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).                 
Error compiling Cython file:
------------------------------------------------------------
...
                            out_data[j, y, i, x] = in_val
                            out_data[j, y_ref, i, x_ref] = ref_val * m_in / m_ref
                        else:
                            out_data[j, y, i, x] = in_val * m_ref / m_in
                            out_data[j, y_ref, i, x_ref] = ref_val
            elif mode == '2':
                        ^
------------------------------------------------------------

src/pyctools/components/pal/transformcore.pyx:61:25: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyctools-pal/./setup.py", line 39, in <module>
    ext_modules = cythonize(find_ext_modules(), compiler_directives={
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1112, in cythonize
    cythonize_one(*args)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1235, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/pyctools/components/pal/transformcore.pyx

```

Note, I try this on aarch64 Android tablet via termux :)

**Comment by jim-easterbrook** [comment]
This same problem (and a solution) is in issue #1 - I really ought to update the source, but it's not one of my priorities at the moment.

Good luck with running it on a tablet - I only ever expected pyctools to be used on "real" computers.  (-:

**Comment by Randrianasulu** [comment]
@jim-easterbrook I think I created pull request with change (compile-tested on tablet).
